export default [
  {
    files: ["**/*.{js,jsx}"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        Promise: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        XMLHttpRequest: "readonly",
        WebSocket: "readonly",
        AbortController: "readonly",
        Intl: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        module: "readonly",
        require: "readonly",
        exports: "readonly"
      },
      parserOptions: {
        ecmaFeatures: {
          jsx: true
        }
      }
    },
    plugins: {
      react: {
        rules: {
          "react/display-name": "off",
          "react/forbid-prop-types": "off",
          "react/jsx-boolean-value": "off",
          "react/jsx-closing-bracket-location": "off",
          "react/jsx-curly-spacing": "off",
          "react/jsx-equals-spacing": "off",
          "react/jsx-handler-names": "off",
          "react/jsx-indent-props": "off",
          "react/jsx-indent": "off",
          "react/jsx-key": "error",
          "react/jsx-max-props-per-line": "off",
          "react/jsx-no-bind": "off",
          "react/jsx-no-duplicate-props": "error",
          "react/jsx-no-literals": "off",
          "react/jsx-no-target-blank": "error",
          "react/jsx-no-undef": "error",
          "react/jsx-pascal-case": "error",
          "react/jsx-sort-props": "off",
          "react/jsx-uses-react": "error",
          "react/jsx-uses-vars": "error",
          "react/no-danger": "off",
          "react/no-deprecated": "error",
          "react/no-did-mount-set-state": "off",
          "react/no-did-update-set-state": "off",
          "react/no-direct-mutation-state": "error",
          "react/no-multi-comp": "off",
          "react/no-set-state": "off",
          "react/no-string-refs": "error",
          "react/no-unknown-property": "error",
          "react/prefer-es6-class": "error",
          "react/prefer-stateless-function": "off",
          "react/prop-types": "off",
          "react/react-in-jsx-scope": "off",
          "react/require-extension": "off",
          "react/self-closing-comp": "off",
          "react/sort-comp": "off",
          "react/wrap-multilines": "off"
        }
      },
      "jsx-a11y": {
        rules: {
          "jsx-a11y/alt-text": "error",
          "jsx-a11y/anchor-has-content": "error",
          "jsx-a11y/anchor-is-valid": "error",
          "jsx-a11y/aria-activedescendant-has-tabindex": "error",
          "jsx-a11y/aria-props": "error",
          "jsx-a11y/aria-proptypes": "error",
          "jsx-a11y/aria-role": "error",
          "jsx-a11y/aria-unsupported-elements": "error",
          "jsx-a11y/click-events-have-key-events": "error",
          "jsx-a11y/control-has-associated-label": "off",
          "jsx-a11y/heading-has-content": "error",
          "jsx-a11y/html-has-lang": "error",
          "jsx-a11y/iframe-has-title": "error",
          "jsx-a11y/img-redundant-alt": "error",
          "jsx-a11y/interactive-supports-focus": "error",
          "jsx-a11y/label-has-associated-control": "error",
          "jsx-a11y/media-has-caption": "error",
          "jsx-a11y/mouse-events-have-key-events": "error",
          "jsx-a11y/no-access-key": "error",
          "jsx-a11y/no-autofocus": "off",
          "jsx-a11y/no-distracting-elements": "error",
          "jsx-a11y/no-interactive-element-to-noninteractive-role": "error",
          "jsx-a11y/no-noninteractive-element-interactions": "error",
          "jsx-a11y/no-noninteractive-element-to-interactive-role": "error",
          "jsx-a11y/no-redundant-roles": "error",
          "jsx-a11y/no-static-element-interactions": "error",
          "jsx-a11y/role-has-required-aria-props": "error",
          "jsx-a11y/role-supports-aria-props": "error",
          "jsx-a11y/scope": "error",
          "jsx-a11y/tabindex-no-positive": "error"
        }
      }
    },
    rules: {
      // Possible Errors
      "no-console": "warn",
      "no-debugger": "error",
      "no-unused-vars": "error",
      "no-undef": "error",
      
      // Best Practices
      "eqeqeq": "error",
      "curly": "error",
      "guard-for-in": "error",
      "no-caller": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-implied-eval": "error",
      "no-iterator": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-loop-func": "error",
      "no-multi-str": "error",
      "no-native-reassign": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-octal-escape": "error",
      "no-proto": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-throw-literal": "error",
      "no-unused-expressions": "error",
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "no-void": "error",
      "no-with": "error",
      "radix": "error",
      "wrap-iife": "error",
      "yoda": "error",
      
      // Variables
      "no-delete-var": "error",
      "no-label-var": "error",
      "no-shadow": "error",
      "no-undef-init": "error",
      
      // Stylistic Issues
      "comma-spacing": "error",
      "eol-last": "error",
      "indent": ["error", 2],
      "keyword-spacing": "error",
      "max-len": ["warn", { "code": 120 }],
      "new-parens": "error",
      "no-mixed-spaces-and-tabs": "error",
      "no-multiple-empty-lines": ["error", { "max": 1 }],
      "no-trailing-spaces": "error",
      "object-curly-spacing": ["error", "always"],
      "quotes": ["error", "single"],
      "semi": ["error", "never"],
      "space-before-blocks": "error",
      "space-before-function-paren": ["error", "never"],
      "space-in-parens": "error",
      "space-infix-ops": "error",
      "space-unary-ops": "error",
      
      // ES6
      "arrow-spacing": "error",
      "constructor-super": "error",
      "generator-star-spacing": "error",
      "no-class-assign": "error",
      "no-const-assign": "error",
      "no-dupe-class-members": "error",
      "no-duplicate-imports": "error",
      "no-new-symbol": "error",
      "no-this-before-super": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-var": "error",
      "object-shorthand": "error",
      "prefer-arrow-callback": "error",
      "prefer-const": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "template-curly-spacing": "error"
    }
  }
]